apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dhpod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dhpod
            image: okteto.dev/dhpod:v0.0.1
          restartPolicy: OnFailure