apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhpb
spec:
  selector:
    matchLabels:
      app: dhpb
  replicas: 1
  template:
    metadata:
      labels:
        app: dhpb
    spec:
      containers:
      - name: dhpb
        image: okteto.dev/dhpb:v0.3.0
        envFrom:
        - configMapRef:
            name: configs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhreply
spec:
  selector:
    matchLabels:
      app: dhreply
  replicas: 1
  template:
    metadata:
      labels:
        app: dhreply
    spec:
      containers:
      - name: dhreply
        image: okteto.dev/dhreply:v0.3.0
        envFrom:
        - configMapRef:
            name: configs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhsub
spec:
  selector:
    matchLabels:
      app: dhsub
  replicas: 1
  template:
    metadata:
      labels:
        app: dhsub
    spec:
      containers:
      - name: dhsub
        image: okteto.dev/dhsub:v0.3.0
        envFrom:
        - configMapRef:
            name: configs
