apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhpb
spec:
  selector:
    matchLabels:
      app: dhpb
  replicas: 1
  template:
    metadata:
      labels:
        app: dhpb
    spec:
      containers:
      - name: dhpb
        image: dhpb
        env: 
          - name: pb_key
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: pb_key
          - name: slack
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: slack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhreply
spec:
  selector:
    matchLabels:
      app: dhreply
  replicas: 1
  template:
    metadata:
      labels:
        app: dhreply
    spec:
      containers:
      - name: dhreply
        image: dhreply
        env: 
          - name: pb_key
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: pb_key
          - name: slack
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: slack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhsub
spec:
  selector:
    matchLabels:
      app: dhsub
  replicas: 1
  template:
    metadata:
      labels:
        app: dhsub
    spec:
      containers:
      - name: dhsub
        image: dhsub
        env: 
          - name: pb_key
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: pb_key
          - name: slack
            valueFrom:
              secretKeyRef:
                name: podsecret
                key: slack
