on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy Application
      uses: okteto/apply@master
      with:
        namespace: mrchypark
        manifest: manifests

    - name: Push API Changes
      uses: okteto/push@master
      with:
        working-directory: pb

    - name: Push Frontend Changes
      uses: okteto/push@master
      with:
        working-directory: reply
        
    - name: Push Frontend Changes
      uses: okteto/push@master
      with:
        working-directory: sub

