name: trigger okteto

on:
  schedule:
    - cron: "0 0,12 * * *"
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Login
      uses: okteto/login@main
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@main
      with:
        namespace: mrchypark

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@main
      with:
        name: podserv

